"""sse_common — shared utilities for SSE services."""

from .channels import (
    CHANNEL_PRICING_DONE,
    CHANNEL_PROCESSOR_DONE,
    CHANNEL_SCRAPER_DONE,
)
from .constants import (
    AVAILABLE_ALGORITHMS,
    MARKET_TIMEZONE,
    REDIS_PRICES_CURRENT_KEY,
    STALENESS_CRITICAL_MINUTES,
    STALENESS_UNAVAILABLE_HOURS,
    STALENESS_WARNING_MINUTES,
    STARTER_TICKERS,
)
from .logging_config import configure_logging

__all__ = [
    "configure_logging",
    "CHANNEL_SCRAPER_DONE",
    "CHANNEL_PROCESSOR_DONE",
    "CHANNEL_PRICING_DONE",
    "AVAILABLE_ALGORITHMS",
    "STARTER_TICKERS",
    "STALENESS_WARNING_MINUTES",
    "STALENESS_CRITICAL_MINUTES",
    "STALENESS_UNAVAILABLE_HOURS",
    "MARKET_TIMEZONE",
    "REDIS_PRICES_CURRENT_KEY",
]
